---
abstract: 'Sign and verify URLs to prevent tampering'
author:
  - 'Companies House <chgovuk@cpan.org>'
build_requires:
  Module::Build: '0.3601'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MojoX-URL-Sign
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Mojo::Base: '0'
  Mojo::URL: '0'
resources:
  bugtracker: https://github.com/companieshouse/MojoX-URL-Sign/issues
  homepage: https://github.com/companieshouse/MojoX-URL-Sign
  repository: https://github.com/companieshouse/MojoX-URL-Sign.git
version: '0.30'
